project:
  type: book
  output-dir: docs
  
book:
  title: Text Analysis for Statistics & Data Science
  author: David Brown
  navbar:
    search: true
    logo: images/text_analysis.png
  repo-url: https://github.com/browndw/textstat_docs
  repo-branch: master
  repo-actions: [issue]
  chapters:
    - index.qmd
    - part: Labs
      chapters:
        - labs/classification-federalist-papers.qmd
        - labs/corpus-basics.qmd
        - labs/processing-pipelines.qmd
        - labs/distributions.qmd
        - labs/collocations.qmd
        - labs/keyness.qmd
        - labs/feature-engineering.qmd
        - labs/logistic-regression.qmd
        - labs/multi-dimensional-analysis.qmd
        - labs/cluster-analysis.qmd
        - labs/time-series.qmd
        - labs/sentiment-and-syuzhet.qmd
        - labs/vector-models.qmd
        - labs/geospacial-mapping.qmd
        - labs/random-forest.qmd
    - part: Labs Sets
      chapters:
         - lab_sets/LabSet_01.qmd
         - lab_sets/LabSet_02.qmd
         - lab_sets/LabSet_03.qmd
         - lab_sets/LabSet_04.qmd
    - part: Report Templates
      chapters:
         - reports/cbe_01.qmd
         - reports/cbe_02.qmd
         - reports/final-project.qmd
    - part: Lectures
      chapters:
         - lectures/embed_linguistic-facts.qmd
         - lectures/embed_llms-history.qmd
         
bibliography: references.bib

format:
  html:
    theme: cosmo